### ISSUE TITLE
It's not working on https

### ISSUE THREAD

**Issue by Korayem** [dep/charmin#6]
I guess it might be due to enforced HTTPS now by TP? because when I config Charmin, the url it shows is HTTP (not secured). Just a guess.

**Comment by dep** [comment]
I'll have a look. Thank you!

**Comment by dep** [comment]
Just pushed v2.0.3 to address this (may take upwards of 60 mins to appear from now). Please have a look and report back if you wouldn't mind.

**Comment by Korayem** [comment]
It's working now.

May I ask why do you need to know the url? can't you just subscribe chrome extension to trigger only if URL has "tpondemand.com"?

**Comment by dep** [comment]
I used to need this for when the extension was used with an older version of TargetProcess and some deprecated functionality. I might actually be able to remove this requirement. I'll see about removing the need for setting that option in the next version.

**Comment by Korayem** [comment]
Glad to know that :)

**Comment by dep** [comment]
Removing the 'project name' requirement as part of 2.0.4. I've uploaded this to the webstore and should be to you shortly.

**Comment by Korayem** [comment]
Awesome! thanks for filling in the gap :)
